/**
 * Comic Generation Queue API
 *
 * Manages the queue of upcoming comic episodes to be generated by the scheduler.
 * Admin can add, remove, and reorder queue items.
 */

import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/lib/auth/session'
import { adminFirestore, initAdmin } from '@/lib/firebase/admin'
import { ComicQueueItem } from '@/types/comic'

// Initialize Firebase Admin
initAdmin()

/**
 * GET - List all queue items (pending first, then by priority)
 */
export async function GET(request: NextRequest) {
  try {
    const session = await getSession()
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const userDoc = await adminFirestore!.collection('users').doc(session.uid).get()
    const userData = userDoc?.data()
    if (!userData?.isAdmin) {
      return NextResponse.json({ error: 'Admin access required' }, { status: 403 })
    }

    // Get status filter from query params (default to all)
    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status') // 'pending', 'processing', 'completed', 'failed', or null for all

    // Build query - where() must come before orderBy() in Firestore
    let query: FirebaseFirestore.Query = adminFirestore!.collection('comic_generation_queue')

    if (status) {
      query = query.where('status', '==', status)
    }

    query = query.orderBy('priority', 'asc')

    const snapshot = await query.limit(50).get()

    const queueItems: ComicQueueItem[] = snapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data(),
      createdAt: doc.data().createdAt?.toDate(),
      scheduledFor: doc.data().scheduledFor?.toDate(),
      processedAt: doc.data().processedAt?.toDate(),
    })) as ComicQueueItem[]

    return NextResponse.json({
      success: true,
      queue: queueItems,
      count: queueItems.length,
    })
  } catch (error) {
    console.error('[API /admin/comics/queue] GET error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to fetch queue' },
      { status: 500 }
    )
  }
}

/**
 * POST - Add a new item to the queue
 */
export async function POST(request: NextRequest) {
  try {
    const session = await getSession()
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const userDoc = await adminFirestore!.collection('users').doc(session.uid).get()
    const userData = userDoc?.data()
    if (!userData?.isAdmin) {
      return NextResponse.json({ error: 'Admin access required' }, { status: 403 })
    }

    const body = await request.json()
    const { theme, location, titleEn, titleJa, characterIds, jlptLevel, scheduledFor } = body

    // Validate required fields
    if (!theme || !location || !characterIds?.length || !jlptLevel) {
      return NextResponse.json(
        { error: 'Missing required fields: theme, location, characterIds, jlptLevel' },
        { status: 400 }
      )
    }

    // Ensure Moshi is always included
    if (!characterIds.includes('moshi-master')) {
      characterIds.unshift('moshi-master')
    }

    // Get highest priority to add new item at the end
    const lastItemSnapshot = await adminFirestore!
      .collection('comic_generation_queue')
      .where('status', '==', 'pending')
      .orderBy('priority', 'desc')
      .limit(1)
      .get()

    const highestPriority = lastItemSnapshot.empty ? 0 : (lastItemSnapshot.docs[0].data().priority || 0)

    // Create queue item
    const queueItem = {
      theme,
      location,
      titleEn: titleEn || null,
      titleJa: titleJa || null,
      characterIds,
      jlptLevel,
      priority: highestPriority + 1,
      status: 'pending',
      createdAt: new Date(),
      createdBy: session.uid,
      scheduledFor: scheduledFor ? new Date(scheduledFor) : null,
    }

    const docRef = await adminFirestore!.collection('comic_generation_queue').add(queueItem)

    return NextResponse.json({
      success: true,
      id: docRef.id,
      queueItem: { id: docRef.id, ...queueItem },
    })
  } catch (error) {
    console.error('[API /admin/comics/queue] POST error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to add to queue' },
      { status: 500 }
    )
  }
}

/**
 * DELETE - Remove an item from the queue
 */
export async function DELETE(request: NextRequest) {
  try {
    const session = await getSession()
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const userDoc = await adminFirestore!.collection('users').doc(session.uid).get()
    const userData = userDoc?.data()
    if (!userData?.isAdmin) {
      return NextResponse.json({ error: 'Admin access required' }, { status: 403 })
    }

    const body = await request.json()
    const { id } = body

    if (!id) {
      return NextResponse.json({ error: 'Missing queue item ID' }, { status: 400 })
    }

    // Check if item exists and is not processing
    const docRef = adminFirestore!.collection('comic_generation_queue').doc(id)
    const doc = await docRef.get()

    if (!doc.exists) {
      return NextResponse.json({ error: 'Queue item not found' }, { status: 404 })
    }

    const itemData = doc.data()
    if (itemData?.status === 'processing') {
      return NextResponse.json(
        { error: 'Cannot delete item that is currently being processed' },
        { status: 400 }
      )
    }

    await docRef.delete()

    return NextResponse.json({
      success: true,
      message: 'Queue item deleted',
    })
  } catch (error) {
    console.error('[API /admin/comics/queue] DELETE error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to delete queue item' },
      { status: 500 }
    )
  }
}

/**
 * PATCH - Update queue item (mainly for reordering)
 */
export async function PATCH(request: NextRequest) {
  try {
    const session = await getSession()
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const userDoc = await adminFirestore!.collection('users').doc(session.uid).get()
    const userData = userDoc?.data()
    if (!userData?.isAdmin) {
      return NextResponse.json({ error: 'Admin access required' }, { status: 403 })
    }

    const body = await request.json()
    const { id, priority, characterIds, jlptLevel, titleEn, titleJa } = body

    if (!id) {
      return NextResponse.json({ error: 'Missing queue item ID' }, { status: 400 })
    }

    const docRef = adminFirestore!.collection('comic_generation_queue').doc(id)
    const doc = await docRef.get()

    if (!doc.exists) {
      return NextResponse.json({ error: 'Queue item not found' }, { status: 404 })
    }

    const itemData = doc.data()
    if (itemData?.status !== 'pending') {
      return NextResponse.json(
        { error: 'Can only update pending items' },
        { status: 400 }
      )
    }

    // Build update object with only provided fields
    const updateData: Record<string, any> = {}
    if (priority !== undefined) updateData.priority = priority
    if (characterIds !== undefined) {
      // Ensure Moshi is always included
      if (!characterIds.includes('moshi-master')) {
        characterIds.unshift('moshi-master')
      }
      updateData.characterIds = characterIds
    }
    if (jlptLevel !== undefined) updateData.jlptLevel = jlptLevel
    if (titleEn !== undefined) updateData.titleEn = titleEn
    if (titleJa !== undefined) updateData.titleJa = titleJa

    if (Object.keys(updateData).length === 0) {
      return NextResponse.json({ error: 'No update fields provided' }, { status: 400 })
    }

    await docRef.update(updateData)

    return NextResponse.json({
      success: true,
      message: 'Queue item updated',
    })
  } catch (error) {
    console.error('[API /admin/comics/queue] PATCH error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to update queue item' },
      { status: 500 }
    )
  }
}
