/**
 * GENERATED FILE - DO NOT EDIT
 * Generated from: config/features.v1.json
 * Generated at: 2026-02-26T11:13:48.288Z
 */

import type { FeatureId } from '@/types/FeatureId'
import { Permission } from '@/lib/access/permissionMap'

export interface FeatureDefinition {
  id: FeatureId
  name: string
  category: string
  lifecycle: 'active' | 'deprecated' | 'hidden'
  permission: Permission
  limitType: 'daily' | 'weekly' | 'monthly'
  notifications: boolean
  description?: string
}

export const FEATURE_REGISTRY: Record<FeatureId, FeatureDefinition> = {
  hiragana_practice: {
    id: 'hiragana_practice',
    name: 'Hiragana Practice',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: true,
    description: 'Practice hiragana characters with SRS-based review sessions',
  },
  katakana_practice: {
    id: 'katakana_practice',
    name: 'Katakana Practice',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: true,
    description: 'Practice katakana characters with SRS-based review sessions',
  },
  kanji_browser: {
    id: 'kanji_browser',
    name: 'Kanji Browser',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Browse and explore kanji with detailed information',
  },
  kanji_connection: {
    id: 'kanji_connection',
    name: 'Kanji Connection',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'monthly',
    notifications: false,
    description: 'Explore kanji families, radicals, and visual patterns to understand kanji relationships',
  },
  kanji_mastery: {
    id: 'kanji_mastery',
    name: 'Kanji Mastery',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Master kanji through progressive learning sessions with stroke order and recognition practice',
  },
  drawing_practice: {
    id: 'drawing_practice',
    name: 'Drawing Practice',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Practice handwriting for kanji and kana with stroke feedback and recognition',
  },
  kanji_drawing_practice: {
    id: 'kanji_drawing_practice',
    name: 'Kanji Drawing Practice',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Practice drawing kanji through repetitive muscle-memory exercises',
  },
  custom_lists: {
    id: 'custom_lists',
    name: 'Custom Lists',
    category: 'organization',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'monthly',
    notifications: false,
    description: 'Create and manage custom learning lists for vocabulary, kanji, and sentences',
  },
  conjugation_drill: {
    id: 'conjugation_drill',
    name: 'Conjugation Drill',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: true,
    description: 'Practice Japanese verb and adjective conjugations with interactive drills',
  },
  drill_focus_mode: {
    id: 'drill_focus_mode',
    name: 'Drill Focus Mode',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: true,
    description: 'Practice conjugations for a single user-selected focus word',
  },
  grammar_explanations: {
    id: 'grammar_explanations',
    name: 'Grammar Explanations',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Get AI-powered grammar explanations for Japanese sentences',
  },
  youtube_shadowing: {
    id: 'youtube_shadowing',
    name: 'YouTube Shadowing',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: true,
    description: 'Practice Japanese pronunciation and listening with YouTube videos and transcript shadowing',
  },
  media_upload: {
    id: 'media_upload',
    name: 'Media File Upload',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Upload and practice with your own video/audio files for shadowing practice',
  },
  save_items: {
    id: 'save_items',
    name: 'Save Items',
    category: 'organization',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'monthly',
    notifications: false,
    description: 'Save vocabulary, kanji, and other items to your personal collection',
  },
  todos: {
    id: 'todos',
    name: 'Todo Lists',
    category: 'organization',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'monthly',
    notifications: false,
    description: 'Create and manage learning todo lists and goals',
  },
  flashcard_decks: {
    id: 'flashcard_decks',
    name: 'Flashcard Decks',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'monthly',
    notifications: false,
    description: 'Create custom flashcard decks for spaced repetition practice',
  },
  anki_imports: {
    id: 'anki_imports',
    name: 'Anki Deck Imports',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'monthly',
    notifications: false,
    description: 'Import decks from Anki (.apkg files)',
  },
  flashcard_daily_reviews: {
    id: 'flashcard_daily_reviews',
    name: 'Flashcard Daily Reviews',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Daily limit for flashcard review sessions',
  },
  stall_layout_customization: {
    id: 'stall_layout_customization',
    name: 'Learning Village Layout Customization',
    category: 'personalization',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Customize the layout of Learning Village stalls by dragging and dropping them to your preferred order',
  },
  pwa_push: {
    id: 'pwa_push',
    name: 'Push Notifications',
    category: 'pwa',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Receive push notifications for study reminders and updates',
  },
  pwa_bg_sync: {
    id: 'pwa_bg_sync',
    name: 'Background Sync',
    category: 'pwa',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Sync study progress in the background when offline',
  },
  pwa_periodic_sync: {
    id: 'pwa_periodic_sync',
    name: 'Periodic Background Sync',
    category: 'pwa',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Periodically sync and prefetch content in the background',
  },
  pwa_share_target: {
    id: 'pwa_share_target',
    name: 'Share Target',
    category: 'pwa',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Share content directly to Moshimoshi from other apps',
  },
  pwa_fs_access: {
    id: 'pwa_fs_access',
    name: 'File System Access',
    category: 'pwa',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Access local files for importing/exporting study materials',
  },
  pwa_badging: {
    id: 'pwa_badging',
    name: 'App Badge',
    category: 'pwa',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Show notification badges on the app icon',
  },
  pwa_media_session: {
    id: 'pwa_media_session',
    name: 'Media Session',
    category: 'pwa',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Control audio playback from system media controls',
  },
  word_lookup: {
    id: 'word_lookup',
    name: 'Word Lookup',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Look up word details including meanings, conjugations, and example sentences',
  },
  kanji_lookup: {
    id: 'kanji_lookup',
    name: 'Kanji Lookup',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Open kanji details including readings, examples, and mnemonics',
  },
  news: {
    id: 'news',
    name: 'News Reading',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Read Japanese news articles with furigana and vocabulary support',
  },
  story: {
    id: 'story',
    name: 'AI Stories',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Read AI-generated stories tailored to your level',
  },
  books: {
    id: 'books',
    name: 'Books Library',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'monthly',
    notifications: false,
    description: 'Access the library of Japanese books and reading materials',
  },
  kanji_mood_board: {
    id: 'kanji_mood_board',
    name: 'Kanji Mood Board',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Explore kanji through visual mood boards and thematic collections',
  },
  drill: {
    id: 'drill',
    name: 'Drill Practice',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Practice vocabulary and kanji with drill exercises',
  },
  blast_mode: {
    id: 'blast_mode',
    name: 'Blast Mode',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'High-intensity adaptive practice sessions with mixed content',
  },
  my_list: {
    id: 'my_list',
    name: 'My List',
    category: 'organization',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Manage your personal study list of saved items',
  },
  textbook_vocabulary: {
    id: 'textbook_vocabulary',
    name: 'Textbook Vocabulary',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'monthly',
    notifications: false,
    description: 'Study vocabulary from popular Japanese textbooks',
  },
  flashcards: {
    id: 'flashcards',
    name: 'Flashcards',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Study with flashcard decks and spaced repetition',
  },
  resources: {
    id: 'resources',
    name: 'Resources',
    category: 'content',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Access learning resources and study materials',
  },
  blogs: {
    id: 'blogs',
    name: 'Blogs',
    category: 'content',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Read blog posts about Japanese language and culture',
  },
  vocabulary: {
    id: 'vocabulary',
    name: 'Vocabulary Browser',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'daily',
    notifications: false,
    description: 'Browse and explore Japanese vocabulary',
  },
  comics: {
    id: 'comics',
    name: 'Moshi Comics',
    category: 'learning',
    lifecycle: 'active',
    permission: Permission.DO_PRACTICE,
    limitType: 'monthly',
    notifications: false,
    description: 'Read Japanese manga-style comics with furigana and vocabulary support',
  }
}

export function getFeature(id: FeatureId): FeatureDefinition {
  return FEATURE_REGISTRY[id]
}

export function getActiveFeatures(): FeatureDefinition[] {
  return Object.values(FEATURE_REGISTRY).filter(f => f.lifecycle === 'active')
}

export function getFeaturesByCategory(category: string): FeatureDefinition[] {
  return Object.values(FEATURE_REGISTRY).filter(f => f.category === category)
}

export function getFeaturesByPermission(permission: Permission): FeatureDefinition[] {
  return Object.values(FEATURE_REGISTRY).filter(f => f.permission === permission)
}
