version: '3.8'

# Redis Cluster Configuration for High Availability
services:
  redis-master:
    image: redis:7-alpine
    container_name: moshimoshi-redis-master
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-master-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CONFIG_PASSWORD=${REDIS_CONFIG_PASSWORD}
    networks:
      - redis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-replica-1:
    image: redis:7-alpine
    container_name: moshimoshi-redis-replica-1
    command: redis-server --slaveof redis-master 6379 --masterauth ${REDIS_PASSWORD} --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - redis-replica-1-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-replica-2:
    image: redis:7-alpine
    container_name: moshimoshi-redis-replica-2
    command: redis-server --slaveof redis-master 6379 --masterauth ${REDIS_PASSWORD} --requirepass ${REDIS_PASSWORD}
    ports:
      - "6381:6379"
    volumes:
      - redis-replica-2-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-sentinel-1:
    image: redis:7-alpine
    container_name: moshimoshi-redis-sentinel-1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
      - redis-sentinel-1-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENTINEL_ANNOUNCE_IP=${EXTERNAL_IP:-127.0.0.1}
      - SENTINEL_ANNOUNCE_PORT=26379
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    restart: unless-stopped

  redis-sentinel-2:
    image: redis:7-alpine
    container_name: moshimoshi-redis-sentinel-2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
      - redis-sentinel-2-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENTINEL_ANNOUNCE_IP=${EXTERNAL_IP:-127.0.0.1}
      - SENTINEL_ANNOUNCE_PORT=26380
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    restart: unless-stopped

  redis-sentinel-3:
    image: redis:7-alpine
    container_name: moshimoshi-redis-sentinel-3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
      - redis-sentinel-3-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENTINEL_ANNOUNCE_IP=${EXTERNAL_IP:-127.0.0.1}
      - SENTINEL_ANNOUNCE_PORT=26381
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    restart: unless-stopped

  # Redis Exporter for Prometheus monitoring
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: moshimoshi-redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis-master:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped

networks:
  redis-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  redis-master-data:
    driver: local
  redis-replica-1-data:
    driver: local
  redis-replica-2-data:
    driver: local
  redis-sentinel-1-data:
    driver: local
  redis-sentinel-2-data:
    driver: local
  redis-sentinel-3-data:
    driver: local