import { NextRequest, NextResponse } from 'next/server'
import ytdl from '@distube/ytdl-core'
import axios from 'axios'
// @ts-expect-error - youtube-captions-scraper has no type declarations
import { getSubtitles } from 'youtube-captions-scraper'
import { Innertube } from 'youtubei.js'
import { adminFirestore as db, Timestamp } from '@/lib/firebase/admin'
import { AIService } from '@/lib/ai/AIService'
import { TranscriptProcessRequest } from '@/lib/ai/types'
import { transcriptCache } from '@/lib/transcript/cache'
import { getSession } from '@/lib/auth/session'
import { evaluate, getTodayBucket } from '@/lib/entitlements/evaluator'
import type { EvalContext } from '@/types/entitlements'
import { cleanYouTubeMetadata, prepareFirestoreData } from '@/lib/firebase/cleanFirestoreData'
import featuresConfig from '../../../../../config/features.v1.json'

// Initialize AI Service
const aiService = AIService.getInstance()

// Helper to assert db is available
function assertDb(): NonNullable<typeof db> {
  if (!db) {
    throw new Error('Database not available')
  }
  return db
}

// YouTube Data API v3 endpoint
const YOUTUBE_API_BASE = 'https://www.googleapis.com/youtube/v3'

let youtubeClient: Innertube | null = null

async function getYouTubeClient() {
  if (!youtubeClient) {
    youtubeClient = await Innertube.create()
  }
  return youtubeClient
}

interface TranscriptLine {
  id: string
  text: string
  startTime: number
  endTime: number
  words?: string[]
  translation?: string
}

interface CaptionTrack {
  language: string
  name: string
  isManual: boolean
  isAutoGenerated: boolean
  trackId: string
}

// Helper function to get available caption tracks using YouTube Data API
async function getAvailableCaptionTracks(videoId: string): Promise<{
  tracks: CaptionTrack[]
  hasJapanese: boolean
} | null> {
  try {
    const apiKey = process.env.GOOGLE_API_KEY || process.env.YOUTUBE_API_KEY
    if (!apiKey) {
      console.warn('YouTube API key not configured, skipping caption detection')
      return null
    }

    const response = await axios.get(`${YOUTUBE_API_BASE}/captions`, {
      params: {
        part: 'snippet',
        videoId: videoId,
        key: apiKey,
      },
      timeout: 5000,
    })

    const tracks = response.data.items.map((track: any) => ({
      language: track.snippet.language,
      name: track.snippet.name,
      isManual: track.snippet.trackKind !== 'ASR',
      isAutoGenerated: track.snippet.trackKind === 'ASR',
      trackId: track.id,
    }))

    return {
      tracks,
      hasJapanese: tracks.some(
        (track: CaptionTrack) => track.language === 'ja' || track.language.startsWith('ja-')
      ),
    }
  } catch (error: any) {
    console.warn('Caption detection failed, continuing with extraction:', error.message)
    return null
  }
}

// Helper function to log API usage
async function logApiUsage(
  api: string,
  success: boolean,
  error?: string,
  metadata?: Record<string, unknown>
) {
  try {
    const firestore = assertDb()
    await firestore.collection('apiUsageLogs').add({
      api,
      success,
      error: error || null, // Firestore doesn't allow undefined values
      metadata: metadata || null,
      timestamp: Timestamp.now(),
    })
  } catch (err) {
    console.error('Failed to log API usage:', err)
  }
}

// Helper function to validate YouTube and YouTube Music URLs
function isValidYouTubeUrl(url: string): boolean {
  // Check standard YouTube URLs
  if (ytdl.validateURL(url)) {
    return true
  }

  // Check YouTube Music URLs
  const youtubeMusicPattern =
    /^https?:\/\/(music\.)?youtube\.com\/(watch|embed)\?v=([a-zA-Z0-9_-]{11})/
  const youtubeMusicShortPattern = /^https?:\/\/music\.youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})/

  return youtubeMusicPattern.test(url) || youtubeMusicShortPattern.test(url)
}

// Helper to extract video ID from YouTube Music URLs
function extractVideoIdFromUrl(url: string): string | null {
  // Try standard extraction first
  try {
    return ytdl.getVideoID(url)
  } catch {
    // Fallback for YouTube Music URLs
    const patterns = [
      /[?&]v=([a-zA-Z0-9_-]{11})/,
      /youtu\.be\/([a-zA-Z0-9_-]{11})/,
      /embed\/([a-zA-Z0-9_-]{11})/,
    ]

    for (const pattern of patterns) {
      const match = url.match(pattern)
      if (match) return match[1]
    }

    return null
  }
}

// Note: Using the new transcriptCache service from /lib/transcript/cache.ts
// The old inline functions have been removed in favor of the singleton service

// Helper function to save video to user's YouTube history
async function saveToYouTubeHistory(
  userId: string,
  videoId: string,
  videoTitle: string,
  videoUrl: string,
  transcript: TranscriptLine[],
  metadata: Record<string, unknown>
): Promise<void> {
  try {
    const firestore = assertDb()
    const docId = `${userId}_${videoId}`
    const docRef = firestore.collection('userYouTubeHistory').doc(docId)

    // Check if document exists
    const doc = await docRef.get()

    if (doc.exists) {
      // Update existing record
      const cleanedMetadata = cleanYouTubeMetadata(metadata || doc.data()?.metadata)
      await docRef.update(
        prepareFirestoreData({
          lastWatched: Timestamp.now(),
          watchCount: (doc.data()?.watchCount || 0) + 1,
          transcript: transcript, // Update transcript if it's better
          metadata: cleanedMetadata,
        })
      )
      console.log('✅ Updated YouTube history for video:', videoId)
    } else {
      // Create new record
      const cleanedMetadata = cleanYouTubeMetadata(metadata)
      await docRef.set(
        prepareFirestoreData({
          userId,
          videoId,
          videoTitle,
          videoUrl,
          transcript,
          metadata: cleanedMetadata,
          firstWatched: Timestamp.now(),
          lastWatched: Timestamp.now(),
          watchCount: 1,
          createdAt: Timestamp.now(),
        })
      )
      console.log('✅ Created new YouTube history entry for video:', videoId)
    }
  } catch (error) {
    console.error('❌ Error saving to YouTube history:', error)
  }
}

// Helper function to check if video has been accessed before (any day)
async function checkIfRepeatVideo(userId: string, videoId: string): Promise<boolean> {
  try {
    const firestore = assertDb()
    const docId = `${userId}_${videoId}`
    const docRef = firestore.collection('userPracticeHistory').doc(docId)
    const doc = await docRef.get()
    return doc.exists
  } catch (error) {
    console.error('❌ Error checking repeat video:', error)
    return false // Assume not repeat on error (safer)
  }
}

// Helper function to determine if video should count toward quota
// Returns true if this is a NEW video (never accessed before)
// Returns false if this is a REPEAT video (unlimited practice)
async function shouldCountTowardQuota(userId: string, videoId: string): Promise<boolean> {
  try {
    const firestore = assertDb()
    const docId = `${userId}_${videoId}`
    const docRef = firestore.collection('userPracticeHistory').doc(docId)
    const doc = await docRef.get()

    if (!doc.exists) {
      // New video, count toward quota
      console.log(`[Quota] New video ${videoId} for user ${userId} - will count toward quota`)
      return true
    }

    // Repeat video, don't count (unlimited practice)
    console.log(`[Quota] Repeat video ${videoId} for user ${userId} - free unlimited practice`)
    return false
  } catch (error) {
    console.error('❌ Error checking quota requirement:', error)
    return true // Assume should count on error (safer for quota limits)
  }
}

// Helper function to create practice history on first video access
// This tracks when user first loaded the video (for quota counting)
async function createPracticeHistoryOnFirstAccess(userId: string, videoId: string): Promise<void> {
  try {
    const firestore = assertDb()
    const docId = `${userId}_${videoId}`
    const docRef = firestore.collection('userPracticeHistory').doc(docId)

    // Double-check it doesn't exist (race condition protection)
    const doc = await docRef.get()
    if (doc.exists) {
      console.log(`[Quota] Practice history already exists for ${videoId}, skipping creation`)
      return
    }

    // Create the document
    await docRef.set({
      userId,
      videoId: `youtube_${videoId}`,
      contentType: 'youtube',
      firstAccessed: Timestamp.now(), // NEW FIELD - when video was first loaded
      firstPracticed: null, // Will be set by /api/practice/track when user watches 30s
      lastPracticed: null, // Will be set by /api/practice/track
      practiceCount: 0, // Will be incremented by /api/practice/track
      totalPracticeTime: 0, // Will be updated by /api/practice/track
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
    })

    console.log(`[Quota] ✅ Created userPracticeHistory for ${videoId} - counted toward quota`)
  } catch (error) {
    console.error('❌ Error creating practice history on first access:', error)
    throw error // Propagate error to prevent quota bypass
  }
}

// Helper function to check user's quota and verify they can access a new video
async function checkAndIncrementQuota(
  userId: string,
  videoId: string,
  userPlan: string
): Promise<{ allowed: boolean; message?: string; quotaInfo?: any }> {
  try {
    // Check if this is a repeat video (should not count toward quota)
    const shouldCount = await shouldCountTowardQuota(userId, videoId)

    if (!shouldCount) {
      // Repeat video - unlimited practice, skip quota check
      console.log(`[Quota] Repeat video - allowing unlimited practice`)
      return { allowed: true }
    }

    // New video - count how many videos user has accessed today
    const today = new Date()
    today.setHours(0, 0, 0, 0)
    const todayTimestamp = Timestamp.fromDate(today)

    // Query userPracticeHistory for videos accessed today
    const firestore = assertDb()
    const practiceSnapshot = await firestore
      .collection('userPracticeHistory')
      .where('userId', '==', userId)
      .get()

    // Count docs with firstAccessed >= today (filtering in memory)
    const todayCount = practiceSnapshot.docs.filter(doc => {
      const data = doc.data()
      return (
        data.contentType === 'youtube' &&
        data.firstAccessed &&
        data.firstAccessed.seconds >= todayTimestamp.seconds
      )
    }).length

    // Get quota limit for user's plan
    const limits: Record<string, number> = {
      guest: 0,
      free: 3,
      premium_monthly: 20,
      premium_yearly: 20,
    }

    const limit = limits[userPlan] || 0

    console.log(`[Quota] Current usage: ${todayCount}/${limit} for plan ${userPlan}`)

    if (todayCount >= limit) {
      // Quota exhausted
      console.log(`[Quota] ❌ Quota exhausted for user ${userId}`)
      return {
        allowed: false,
        message: 'Daily video limit reached',
        quotaInfo: {
          used: todayCount,
          limit,
          remaining: 0,
          resetAt: new Date(today.getTime() + 24 * 60 * 60 * 1000).toISOString(),
        },
      }
    }

    // Quota available - create practice history to increment quota
    console.log(`[Quota] ✅ Quota available, creating userPracticeHistory`)
    await createPracticeHistoryOnFirstAccess(userId, videoId)

    return { allowed: true }
  } catch (error) {
    console.error('❌ Error checking and incrementing quota:', error)
    // Allow access on error (fail open for better UX)
    return { allowed: true }
  }
}

// Helper function to format transcript with AI
async function formatTranscriptWithAI(
  transcript: any[],
  videoTitle?: string,
  contentId?: string
): Promise<any[] | null> {
  try {
    // Skip if transcript too short
    if (transcript.length < 3) {
      console.log('🤖 [AI] Skipping formatting - transcript too short')
      return null
    }

    console.log('🤖 [AI] Starting AI formatting for', transcript.length, 'segments')

    // Use the improved processTranscript method directly
    const response = await aiService.processTranscript(
      {
        content: {
          transcript: transcript.map(seg => ({
            text: seg.text || '',
            startTime: seg.startTime || 0,
            endTime: seg.endTime || 0,
          })),
          videoTitle,
          language: 'ja',
        },
        splitForShadowing: true,
        maxSegmentLength: 20,
        addFurigana: false,
        includeTranslations: true,
      },
      {
        jlptLevel: 'N4',
        includeTranslations: true,
      }
    )

    if (!response.success || !response.data) {
      console.error('❌ [AI] Failed to format transcript:', response.error)
      return null
    }

    // Validate segments before processing
    const segments = response.data.segments || []
    const validSegments = segments.filter(
      seg => seg && seg.text && typeof seg.text === 'string' && seg.text.trim().length > 0
    )

    if (validSegments.length === 0) {
      console.error('❌ [AI] No valid segments in response')
      return null
    }

    // Calculate proper timing if needed
    const totalDuration = transcript[transcript.length - 1].endTime - transcript[0].startTime
    const fullText = transcript.map(line => line.text || '').join('')
    const avgTimePerChar = fullText.length > 0 ? totalDuration / fullText.length : 3
    let currentTime = transcript[0].startTime || 0

    // Convert to the expected format with proper timing
    const formattedTranscript = validSegments.map((seg, index) => {
      const duration = seg.text.length * avgTimePerChar
      const result = {
        id: seg.id || `seg_${index + 1}`,
        text: seg.text,
        startTime: seg.startTime !== undefined ? seg.startTime : currentTime,
        endTime: seg.endTime !== undefined ? seg.endTime : currentTime + duration,
        words: [seg.text],
        translation: seg.translation,
      }

      // Update currentTime for next segment if we're calculating
      if (seg.startTime === undefined) {
        currentTime += duration
      }

      return result
    })

    // Log statistics
    const lengths = formattedTranscript.map(s => s.text.length)
    const avgLength = lengths.reduce((a, b) => a + b, 0) / lengths.length
    const longSegments = lengths.filter(l => l > 20).length

    console.log(`✅ [AI] Successfully formatted ${formattedTranscript.length} segments`)
    console.log(
      `📊 [AI] Avg length: ${avgLength.toFixed(1)} chars, Long segments (>20): ${longSegments}/${formattedTranscript.length}`
    )

    if (response.cached) {
      console.log(`💾 [AI] Response was cached`)
    }

    if (response.usage) {
      console.log(
        `💰 [AI] Cost: $${response.usage.estimatedCost.toFixed(4)} | Tokens: ${response.usage.totalTokens}`
      )
    }

    if (longSegments > 0) {
      console.warn(
        `⚠️ [AI] ${longSegments} segments exceed 20 chars - may be difficult for shadowing`
      )
    }

    return formattedTranscript
  } catch (error: any) {
    console.error('❌ [AI] Error formatting transcript:', error)
    console.error('❌ [AI] Error details:', {
      name: error?.name || 'Unknown',
      message: error?.message || String(error),
      code: error?.code,
      details: error?.details,
    })
    return null
  }
}

async function extractWithYouTubeNative(
  videoId: string | null,
  contentId: string,
  url: string,
  isAuthenticated: boolean,
  userId: string
): Promise<NextResponse | null> {
  if (!videoId) {
    return null
  }

  try {
    const client = await getYouTubeClient()
    const videoInfo = await client.getInfo(videoId)
    const transcriptInfo = await videoInfo.getTranscript()

    const languageMenu = transcriptInfo?.transcript?.content?.footer?.language_menu
    const availableLanguages: any[] = languageMenu?.sub_menu_items || []

    const japaneseLanguages = availableLanguages.filter(lang => {
      const title = (lang.title || '').toLowerCase()
      return (
        (title.includes('japanese') || title.includes('日本語')) &&
        !title.includes('english') &&
        !title.includes('英語')
      )
    })

    if (japaneseLanguages.length === 0) {
      await logApiUsage('youtubei.js', false, 'NO_JAPANESE_TRANSCRIPT', {
        videoId,
        availableLanguages: availableLanguages.map(lang => lang.title),
      })
      return null
    }

    // Use flexible type to allow both original transcriptInfo and custom format
    let finalTranscriptInfo: { transcript?: any } | typeof transcriptInfo = transcriptInfo
    let selectedLanguage = availableLanguages.find((lang: any) => lang.selected)
    let forcedJapanese = false

    const isCurrentlyJapanese =
      (selectedLanguage?.title || '').toLowerCase().includes('japanese') ||
      (selectedLanguage?.title || '').toLowerCase().includes('日本語')

    if (!isCurrentlyJapanese) {
      const preferredJapanese =
        japaneseLanguages.find(
          lang => !(lang.title || '').toLowerCase().includes('auto-generated')
        ) || japaneseLanguages[0]

      if (preferredJapanese?.continuation) {
        try {
          const payload = {
            context: client.session?.context,
            continuation: preferredJapanese.continuation,
          }

          let response: any = null

          // Access internal youtubei.js methods with type assertion (internal API)
          /* eslint-disable @typescript-eslint/no-unsafe-function-type */
          const session = client.session as
            | { http?: { post?: Function }; actions?: { execute?: Function } }
            | undefined
          /* eslint-enable @typescript-eslint/no-unsafe-function-type */
          if (typeof session?.http?.post === 'function') {
            response = await session.http.post('/youtubei/v1/get_transcript', payload)
          } else if (typeof session?.actions?.execute === 'function') {
            response = await session.actions.execute('/youtubei/v1/get_transcript', payload)
          }

          const transcriptContent =
            response?.actions?.[0]?.updateEngagementPanelAction?.content?.transcript ??
            response?.data?.actions?.[0]?.updateEngagementPanelAction?.content?.transcript ??
            response?.transcript

          if (transcriptContent) {
            finalTranscriptInfo = { transcript: transcriptContent }
            selectedLanguage = preferredJapanese
            forcedJapanese = true
          }
        } catch (continuationError) {
          console.warn('[YouTubei] Failed to force Japanese transcript:', continuationError)
        }
      }
    } else {
      forcedJapanese = true
    }

    const rawSegments = finalTranscriptInfo?.transcript?.content?.body?.initial_segments

    if (!rawSegments || rawSegments.length === 0) {
      await logApiUsage('youtubei.js', false, 'NO_SEGMENTS', { videoId })
      return null
    }

    const segments = rawSegments
      .map((segment: any) => {
        const startMs = Number(segment.start_ms ?? 0)
        const endMs = Number(segment.end_ms ?? startMs)
        const start = startMs / 1000
        const end = endMs / 1000
        const text = segment.snippet?.text || segment.snippet?.runs?.[0]?.text || ''

        return {
          start,
          end,
          text: text.trim(),
        }
      })
      .filter((segment: any) => segment.text.length > 0 && !/^\[.*\]$/.test(segment.text))

    if (segments.length === 0) {
      await logApiUsage('youtubei.js', false, 'EMPTY_SEGMENTS', { videoId })
      return null
    }

    const languageTitle =
      selectedLanguage?.title || (forcedJapanese ? 'Japanese (forced)' : 'Unknown')
    const isJapanese =
      forcedJapanese ||
      languageTitle.toLowerCase().includes('japanese') ||
      languageTitle.toLowerCase().includes('日本語')

    if (!isJapanese) {
      await logApiUsage('youtubei.js', false, 'NON_JAPANESE_TRANSCRIPT', {
        videoId,
        language: languageTitle,
      })
      return null
    }

    const transcript = segments.map((segment: any, index: number) => ({
      id: String(index + 1),
      text: segment.text,
      startTime: segment.start,
      endTime: segment.end,
      words: segment.text.split(/[\s、。！？]/g).filter((w: string) => w.length > 0),
    }))

    // Cast to any to access extended properties not in base type definition
    const basicInfo = (videoInfo?.basic_info || {}) as Record<string, any>
    const videoMetadata = {
      title: basicInfo.title,
      channelTitle: basicInfo.author,
      description: basicInfo.description,
      thumbnails: basicInfo.thumbnail?.thumbnails,
      duration: basicInfo.duration,
      publishedAt: basicInfo.publish_date,
    }

    const canBackgroundFormat = isAuthenticated && userId && userId !== 'anonymous'
    let formattedTranscript: any[] | null = null
    let formattingPending = false

    if (canBackgroundFormat) {
      try {
        await transcriptCache.set({
          contentId,
          contentType: 'youtube',
          videoUrl: url,
          videoTitle: videoMetadata.title || `YouTube Video ${videoId}`,
          transcript,
          language: 'ja',
          metadata: {
            youtubeVideoId: videoId,
            channelName: videoMetadata.channelTitle,
            uploadDate: videoMetadata.publishedAt,
            thumbnailUrl: videoMetadata.thumbnails?.[0]?.url,
            thumbnails: videoMetadata.thumbnails,
            description: videoMetadata.description,
            wasFormatted: false,
            method: 'youtubei.js',
            forcedJapanese,
          },
        })
      } catch (cacheError) {
        console.error('[YouTubei] Failed to cache transcript:', cacheError)
      }

      formattingPending = true

      void (async () => {
        try {
          const aiFormatted = await formatTranscriptWithAI(
            transcript,
            videoMetadata.title,
            contentId
          )
          if (aiFormatted && aiFormatted.length > 0) {
            await transcriptCache.set({
              contentId,
              contentType: 'youtube',
              videoUrl: url,
              videoTitle: videoMetadata.title || `YouTube Video ${videoId}`,
              transcript: aiFormatted,
              formattedTranscript: aiFormatted,
              language: 'ja',
              metadata: {
                youtubeVideoId: videoId,
                channelName: videoMetadata.channelTitle,
                uploadDate: videoMetadata.publishedAt,
                thumbnailUrl: videoMetadata.thumbnails?.[0]?.url,
                thumbnails: videoMetadata.thumbnails,
                description: videoMetadata.description,
                wasFormatted: true,
                method: 'youtubei.js',
                forcedJapanese,
              },
            })
          }
        } catch (formatError) {
          console.warn('[YouTubei] Background AI formatting failed:', formatError)
        }
      })()
    } else {
      try {
        formattedTranscript = await formatTranscriptWithAI(
          transcript,
          videoMetadata.title,
          contentId
        )
      } catch (formatError) {
        console.warn(
          '[YouTubei] AI formatting failed, continuing without formatted transcript:',
          formatError
        )
      }
    }

    if (isAuthenticated && userId && userId !== 'anonymous') {
      try {
        await saveToYouTubeHistory(
          userId,
          videoId,
          videoMetadata.title || `YouTube Video ${videoId}`,
          url,
          formattedTranscript || transcript,
          {
            channelTitle: videoMetadata.channelTitle,
            thumbnails: videoMetadata.thumbnails,
            duration: videoMetadata.duration,
            publishedAt: videoMetadata.publishedAt,
          }
        )
      } catch (historyError) {
        console.error('[YouTubei] Failed to save history:', historyError)
      }
    }

    await logApiUsage('youtubei.js', true, undefined, {
      videoId,
      language: languageTitle,
      forcedJapanese,
      segmentCount: transcript.length,
      formattingPending,
    })

    return NextResponse.json({
      success: true,
      transcript,
      formattedTranscript,
      language: 'ja',
      videoTitle: videoMetadata.title || `YouTube Video ${videoId}`,
      videoMetadata,
      method: 'youtubei.js',
      hasFormattedVersion: !!formattedTranscript,
      forcedJapanese,
      formattingPending,
    })
  } catch (error: any) {
    console.error('[YouTubei] Error fetching transcript:', error)
    await logApiUsage('youtubei.js', false, error?.message || 'UNKNOWN_ERROR', { videoId })
    return null
  }
}

// Helper function to extract with YouTube-Transcript.io
async function extractWithYouTubeTranscriptIO(
  videoId: string | null,
  apiKey: string | undefined,
  contentId: string,
  isAuthenticated: boolean,
  videoMetadata: any,
  url: string
): Promise<NextResponse> {
  try {
    if (!videoId) {
      return NextResponse.json({
        success: false,
        error: 'INVALID_VIDEO_ID',
        message: 'Could not extract video ID from URL',
      })
    }

    // YouTube-Transcript.io API endpoint
    const apiUrl = `https://youtube-transcript.io/api/transcript`

    // Prepare request parameters
    const params: any = {
      video_id: videoId,
      lang: 'ja', // Request Japanese transcripts
    }

    // Add API key if provided (for paid plans)
    const headers: any = {
      Accept: 'application/json',
      'User-Agent': 'Moshimoshi/1.0',
    }

    if (apiKey) {
      headers['Authorization'] = `Bearer ${apiKey}`
    }

    const response = await axios.get(apiUrl, {
      params,
      headers,
      timeout: 15000,
    })

    if (response.data && response.data.transcript) {
      const transcript = response.data.transcript.map((segment: any, index: number) => ({
        id: String(index + 1),
        text: segment.text || '',
        startTime: segment.start || index * 5,
        endTime: segment.end || segment.start + segment.duration || (index + 1) * 5,
        words: (segment.text || '').split(/[\s、。！？]/g).filter((w: string) => w.length > 0),
      }))

      // Save to cache only for authenticated users
      if (isAuthenticated) {
        try {
          await transcriptCache.set({
            contentId,
            contentType: 'youtube',
            videoUrl: url,
            videoTitle: videoMetadata?.title || response.data.title || 'Unknown',
            transcript,
            language: response.data.language || 'ja',
            metadata: {
              youtubeVideoId: videoId,
              channelName: videoMetadata?.channelTitle,
              uploadDate: videoMetadata?.publishedAt,
              thumbnailUrl: videoMetadata?.thumbnails?.medium?.url,
              duration: videoMetadata?.duration,
              method: 'youtube-transcript-io',
            },
          })
        } catch (cacheError) {
          console.error('Failed to cache transcript:', cacheError)
        }
      }

      // Format transcript with AI if it's Japanese
      let formattedTranscript = null
      if ((response.data.language || 'ja').startsWith('ja')) {
        formattedTranscript = await formatTranscriptWithAI(
          transcript,
          videoMetadata?.title || response.data.title,
          contentId
        )
      }

      await logApiUsage('youtube-transcript-io', true, undefined, { videoId })

      // Only cache if we have the AI-processed version
      if (formattedTranscript && formattedTranscript.length > 0) {
        await transcriptCache.set({
          contentId,
          contentType: 'youtube',
          transcript: formattedTranscript, // Use AI-processed version as main transcript
          formattedTranscript: formattedTranscript,
          language: response.data.language || 'ja',
          videoUrl: url,
          videoTitle: videoMetadata?.title || response.data.title || 'Unknown',
          metadata: {
            youtubeVideoId: videoId,
            channelName: videoMetadata?.channelTitle,
            uploadDate: videoMetadata?.publishedAt,
            thumbnailUrl: videoMetadata?.thumbnails?.high?.url,
            thumbnails: videoMetadata?.thumbnails,
            description: videoMetadata?.description,
            wasFormatted: true,
            formattingModel: 'gpt-3.5-turbo',
          },
        })
        console.log('✅ Cached AI-processed transcript for:', videoId)
      } else {
        console.log('⏭️ Skipping cache - no AI-processed transcript available')
      }

      return NextResponse.json({
        success: true,
        transcript,
        formattedTranscript,
        language: response.data.language || 'ja',
        videoTitle: videoMetadata?.title || response.data.title || 'Unknown',
        videoMetadata: videoMetadata,
        method: 'youtube-transcript-io',
        hasFormattedVersion: !!formattedTranscript,
      })
    } else {
      throw new Error('No transcript data in response')
    }
  } catch (error: any) {
    console.error('YouTube-Transcript.io error:', error.message)

    await logApiUsage('youtube-transcript-io', false, error.message, { videoId })

    // Handle specific error cases
    if (error.response?.status === 429) {
      return NextResponse.json({
        success: false,
        error: 'RATE_LIMIT',
        message:
          'YouTube-Transcript.io rate limit exceeded. Please try again later or use a different provider.',
      })
    } else if (error.response?.status === 401) {
      return NextResponse.json({
        success: false,
        error: 'AUTH_FAILED',
        message: 'Invalid API key for YouTube-Transcript.io. Please check your API key.',
      })
    } else if (error.response?.status === 404) {
      return NextResponse.json({
        success: false,
        error: 'NO_TRANSCRIPT',
        message: 'No transcript available for this video on YouTube-Transcript.io',
      })
    }

    return NextResponse.json({
      success: false,
      error: 'EXTRACTION_FAILED',
      message: error.message || 'Failed to extract transcript via YouTube-Transcript.io',
    })
  }
}

export async function POST(request: NextRequest) {
  try {
    const {
      url,
      provider = 'auto',
      forceRegenerate = false,
      forceReformat = false,
      apiKey,
      // Progressive enhancement parameters
      enhanceOnly = false,
      rawTranscript = null,
    } = await request.json()

    // ═══════════════════════════════════════════════════════
    // ENHANCE ONLY MODE: Phase 2 of progressive loading
    // Takes raw transcript and enhances it with AI
    // ═══════════════════════════════════════════════════════
    if (enhanceOnly && rawTranscript && Array.isArray(rawTranscript)) {
      console.log(
        '🚀 [ENHANCE-ONLY] Processing AI enhancement for',
        rawTranscript.length,
        'segments'
      )

      try {
        const formattedTranscript = await formatTranscriptWithAI(
          rawTranscript,
          undefined, // videoTitle not critical for enhancement
          undefined // contentId not critical for enhancement
        )

        if (!formattedTranscript) {
          return NextResponse.json(
            {
              success: false,
              error: 'AI_ENHANCEMENT_FAILED',
              message: 'Failed to enhance transcript with AI',
            },
            { status: 500 }
          )
        }

        console.log(
          '✅ [ENHANCE-ONLY] AI enhancement complete:',
          formattedTranscript.length,
          'segments'
        )

        return NextResponse.json({
          success: true,
          formattedTranscript,
          method: 'ai-enhancement-only',
        })
      } catch (error: any) {
        console.error('❌ [ENHANCE-ONLY] Error:', error)
        return NextResponse.json(
          {
            success: false,
            error: 'AI_ENHANCEMENT_ERROR',
            message: error.message || 'Failed to enhance transcript',
          },
          { status: 500 }
        )
      }
    }

    if (!url || !isValidYouTubeUrl(url)) {
      return NextResponse.json({ error: 'Invalid YouTube or YouTube Music URL' }, { status: 400 })
    }

    // Get session to get user information
    let session = null
    let isAuthenticated = false
    let userId = 'anonymous'

    try {
      session = await getSession()
      console.log('🔐 [DEBUG] Raw session:', session)
      isAuthenticated = !!session
      userId = session?.uid || 'anonymous'
    } catch (sessionError) {
      console.error('🔐 [ERROR] Failed to get session:', sessionError)
      // Continue without authentication - allow anonymous access
      isAuthenticated = false
      userId = 'anonymous'
    }

    console.log('🔐 [AUTH] Session validation:', {
      isAuthenticated,
      userId,
      userEmail: session?.email || 'none',
      tier: session?.tier,
      sessionData: session,
    })

    // Extract video ID for YouTube API calls (need this BEFORE creating contentId)
    const videoId = extractVideoIdFromUrl(url)

    // Validate videoId before proceeding
    if (!videoId) {
      return NextResponse.json(
        {
          success: false,
          error: 'INVALID_URL',
          message: 'Could not extract video ID from URL',
        },
        { status: 400 }
      )
    }

    // CHECK CAPTION AVAILABILITY using YouTube Data API
    console.log('🔍 Checking available caption tracks...')
    const captionInfo = await getAvailableCaptionTracks(videoId)

    if (captionInfo) {
      console.log(
        '📋 Available tracks:',
        captionInfo.tracks.map(t => `${t.language} (${t.isManual ? 'manual' : 'auto'})`)
      )

      if (!captionInfo.hasJapanese) {
        // No Japanese captions available - provide helpful error
        const availableLanguages = [...new Set(captionInfo.tracks.map(t => t.language))]

        return NextResponse.json({
          success: false,
          error: 'NO_JAPANESE_CAPTIONS',
          message: `This video has captions in: ${availableLanguages.join(', ')}, but not Japanese.`,
          availableLanguages,
          suggestions: [
            'Try videos with Japanese subtitles',
            'Upload the audio file directly for AI transcription',
            'Look for videos with manual Japanese captions (usually better quality)',
          ],
        })
      }
    } else {
      console.log('⚠️ Could not verify caption availability, proceeding with extraction')
    }

    // CHECK QUOTA for authenticated users BEFORE extracting transcript
    // This ensures new videos count toward quota even if transcript is cached
    if (isAuthenticated && userId && userId !== 'anonymous') {
      // Get user's plan from Firestore
      let userPlan = 'free'
      try {
        const firestore = assertDb()
        const userDoc = await firestore.collection('users').doc(userId).get()
        if (userDoc.exists) {
          const userData = userDoc.data()
          userPlan = userData?.subscription?.plan || 'free'
        }
      } catch (error) {
        console.error('[Quota] Error fetching user plan:', error)
        // Continue with 'free' as default
      }

      // Check and increment quota
      const quotaCheck = await checkAndIncrementQuota(userId, videoId, userPlan)

      if (!quotaCheck.allowed) {
        // Quota exhausted - return error
        return NextResponse.json(
          {
            success: false,
            error: 'QUOTA_EXCEEDED',
            message: quotaCheck.message || 'Daily video limit reached',
            quotaInfo: quotaCheck.quotaInfo,
          },
          { status: 429 }
        ) // 429 Too Many Requests
      }
    }

    // Check cache FIRST before making any API calls
    const contentId = `youtube_${videoId}`

    // Skip cache if force regenerate is requested
    if (!forceRegenerate) {
      const cachedTranscript = await transcriptCache.get(contentId)

      if (cachedTranscript && cachedTranscript.transcript.length > 0) {
        // Save to YouTube history even for cached videos (to update watch count)
        if (isAuthenticated && userId && userId !== 'anonymous') {
          await saveToYouTubeHistory(
            userId,
            videoId,
            cachedTranscript.videoTitle || 'Unknown',
            url,
            cachedTranscript.formattedTranscript || cachedTranscript.transcript,
            cachedTranscript.metadata || {}
          )
        }

        return NextResponse.json({
          success: true,
          transcript: cachedTranscript.transcript,
          formattedTranscript: cachedTranscript.formattedTranscript || null,
          language: cachedTranscript.language,
          videoTitle: cachedTranscript.videoTitle,
          videoMetadata: cachedTranscript.metadata,
          method: 'cache',
          fromCache: true,
          hasFormattedVersion: !!cachedTranscript.formattedTranscript,
        })
      }
    }
    // Attempt YouTube native transcripts first (youtubei.js) before other providers
    const shouldTryYouTubeNative = provider === 'youtube-native' || provider === 'auto'

    if (shouldTryYouTubeNative) {
      const youtubeNativeResult = await extractWithYouTubeNative(
        videoId,
        contentId,
        url,
        isAuthenticated,
        userId
      )

      if (youtubeNativeResult) {
        return youtubeNativeResult
      }
    }

    let videoMetadata = null
    let hitRateLimit = false // Track if we hit rate limits

    // Provider-specific extraction
    if (provider === 'youtube-transcript-io') {
      return await extractWithYouTubeTranscriptIO(
        videoId,
        apiKey,
        contentId,
        isAuthenticated,
        videoMetadata,
        url
      )
    } else if (provider === 'youtube-native') {
      // Continue with OAuth/native methods below
    } else if (provider === 'whisper') {
      // This would require audio extraction - not implemented yet
      return NextResponse.json({
        success: false,
        error: 'PROVIDER_NOT_IMPLEMENTED',
        message: 'Whisper provider requires audio extraction which is not yet implemented',
      })
    }

    // Try to get video metadata using server-side API key
    const GOOGLE_API_KEY = process.env.YOUTUBE_API_KEY || process.env.GOOGLE_API_KEY

    if (GOOGLE_API_KEY) {
      try {
        const videoResponse = await axios.get(`${YOUTUBE_API_BASE}/videos`, {
          params: {
            part: 'snippet,contentDetails',
            id: videoId,
            key: GOOGLE_API_KEY,
          },
        })

        if (videoResponse.data.items && videoResponse.data.items.length > 0) {
          const video = videoResponse.data.items[0]
          videoMetadata = {
            title: video.snippet.title,
            channelTitle: video.snippet.channelTitle,
            description: video.snippet.description,
            thumbnails: video.snippet.thumbnails,
            duration: video.contentDetails.duration,
            publishedAt: video.snippet.publishedAt,
          }
        }
      } catch (youtubeApiError: unknown) {
        const errorMessage =
          youtubeApiError instanceof Error ? youtubeApiError.message : String(youtubeApiError)
        console.error('YouTube Data API error:', errorMessage)
        const axiosError = youtubeApiError as { response?: { status?: number; data?: unknown } }
        if (axiosError.response) {
          console.error('API Response:', axiosError.response.status, axiosError.response.data)
        }
        // Continue with other methods - don't let this block SupaData
      }
    } else {
    }

    // Method 2: Try SupaData AI for transcripts (with better error handling)
    const SUPA_API_KEY = process.env.SUPA_YOUTUBE_API_KEY

    if (SUPA_API_KEY) {
      // Enhanced retry logic with exponential backoff for SupaData API
      let supaResponse = null
      let lastError = null
      const maxRetries = 2 // Reduced retries to save API calls

      for (let attempt = 0; attempt < maxRetries; attempt++) {
        try {
          console.log(`=== Trying SupaData AI (attempt ${attempt + 1}/${maxRetries}) ===`)
          console.log('SupaData API Key first 10 chars:', SUPA_API_KEY.substring(0, 10) + '...')

          // Exponential backoff: 0ms, 1000ms
          if (attempt > 0) {
            const backoffDelay = Math.min(1000 * Math.pow(2, attempt - 1), 5000)
            console.log(`Waiting ${backoffDelay}ms before retry (exponential backoff)...`)
            await new Promise(resolve => setTimeout(resolve, backoffDelay))
          }

          supaResponse = await axios.get(`https://api.supadata.ai/v1/transcript`, {
            params: {
              url,
              lang: 'ja', // Request Japanese subtitles specifically
            },
            headers: {
              'x-api-key': SUPA_API_KEY,
            },
            timeout: 30000, // 30 second timeout
          })

          // If successful, break out of retry loop
          if (supaResponse && supaResponse.data) {
            await logApiUsage('supadata', true, undefined, { videoId, attempt: attempt + 1 })
            break
          }
        } catch (error: any) {
          lastError = error
          console.error(`SupaData attempt ${attempt + 1} failed:`, error.message)

          // Special handling for different error types
          if (error.response?.status === 429) {
            console.warn('⚠️ SupaData rate limit exceeded (429) - Monthly limit reached')

            hitRateLimit = true
            await logApiUsage('supadata', false, 'rate_limit_exceeded', { videoId, status: 429 })
            // Don't retry on 429, just move to fallback methods
            break
          } else if (error.response?.status === 401) {
            console.error('❌ SupaData API key invalid or expired (401)')
            break // Don't retry on auth errors
          } else if (error.response?.status === 403) {
            console.error('❌ SupaData API key forbidden - check permissions (403)')
            break // Don't retry on permission errors
          } else if (error.response?.status === 404) {
            break // Don't retry if transcript doesn't exist
          }

          // Only retry on network errors or 5xx server errors
          const shouldRetry = !error.response || error.response.status >= 500
          if (!shouldRetry || attempt === maxRetries - 1) {
            break
          }
        }
      }

      if (supaResponse && supaResponse.data) {
        console.log('SupaData response data keys:', Object.keys(supaResponse.data || {}))

        // Check if Japanese subtitles are available
        const hasJapanese =
          supaResponse.data.lang === 'ja' ||
          supaResponse.data.lang?.startsWith('ja') ||
          supaResponse.data.availableLangs?.some((lang: string) => lang.startsWith('ja'))

        if (!hasJapanese) {
          console.warn(
            '⚠️ No Japanese subtitles available, using available language:',
            supaResponse.data.lang
          )
          // Continue with available language instead of throwing error
          // Many Japanese learning videos might have English subtitles
        }

        // Parse SupaData response to our format
        const transcript = parseSupaDataTranscript(supaResponse.data)

        if (transcript && transcript.length > 0) {
          // Save to cache only for authenticated users
          if (isAuthenticated) {
            console.log('=== Saving to transcript cache (authenticated user) ===')

            try {
              await transcriptCache.set({
                contentId,
                contentType: 'youtube',
                videoUrl: url,
                videoTitle: videoMetadata?.title || supaResponse.data.title || 'Unknown',
                transcript,
                language: 'ja',
                metadata: {
                  youtubeVideoId: videoId,
                  channelName: videoMetadata?.channelTitle,
                  uploadDate: videoMetadata?.publishedAt,
                  thumbnailUrl:
                    videoMetadata?.thumbnails?.medium?.url ||
                    videoMetadata?.thumbnails?.default?.url,
                  duration: videoMetadata?.duration,
                  method: 'supadata-ai',
                },
              })
            } catch (cacheError) {
              console.error('=== Cache save failed ===', cacheError)
            }
          } else {
          }

          // Format transcript with AI for Japanese content
          // TEMPORARILY: Always try formatting for testing
          let formattedTranscript = null
          const isJapaneseContent =
            hasJapanese ||
            videoMetadata?.title?.match(/[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF]/) ||
            transcript.some(t => t.text?.match(/[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF]/))

          if (isJapaneseContent || true) {
            // Always format for testing
            console.log(
              '🤖 [EXTRACT] Attempting AI formatting (language:',
              supaResponse.data.lang,
              ')'
            )
            formattedTranscript = await formatTranscriptWithAI(
              transcript,
              videoMetadata?.title || supaResponse.data.title,
              contentId
            )
          }

          // Only cache if we have the AI-processed version
          if (formattedTranscript && formattedTranscript.length > 0) {
            await transcriptCache.set({
              contentId,
              contentType: 'youtube',
              transcript: formattedTranscript, // Use AI-processed version as main transcript
              formattedTranscript: formattedTranscript,
              language: 'ja',
              videoUrl: url,
              videoTitle: videoMetadata?.title || supaResponse.data.title || 'Unknown',
              metadata: {
                youtubeVideoId: videoId,
                channelName: videoMetadata?.channelTitle,
                uploadDate: videoMetadata?.publishedAt,
                thumbnailUrl: videoMetadata?.thumbnails?.high?.url,
                thumbnails: videoMetadata?.thumbnails,
                description: videoMetadata?.description,
                wasFormatted: true,
                formattingModel: 'gpt-3.5-turbo',
              },
            })
            console.log('✅ Cached AI-processed transcript for:', videoId)
          } else {
            console.log('⏭️ Skipping cache - no AI-processed transcript available')
          }

          // Save to YouTube history if user is authenticated
          if (isAuthenticated && userId && userId !== 'anonymous') {
            await saveToYouTubeHistory(
              userId,
              videoId,
              videoMetadata?.title || supaResponse.data.title || 'Unknown',
              url,
              formattedTranscript || transcript,
              {
                channelTitle: videoMetadata?.channelTitle,
                thumbnails: videoMetadata?.thumbnails,
                duration: videoMetadata?.duration,
                publishedAt: videoMetadata?.publishedAt,
              }
            )
          }

          return NextResponse.json({
            success: true,
            transcript,
            formattedTranscript,
            language: supaResponse.data.lang || 'ja',
            isAutoGenerated: false, // SupaData provides quality transcripts
            videoTitle: videoMetadata?.title || supaResponse.data.title || 'Unknown',
            videoMetadata: videoMetadata,
            method: 'supadata-ai',
            hasFormattedVersion: !!formattedTranscript,
            availableLanguages: supaResponse.data.availableLangs || [supaResponse.data.lang],
          })
        }
      } else if (lastError) {
        // Handle error if all retries failed
        console.error('=== SupaData AI error after all retries ===')
        console.error('Error message:', lastError.message)
        console.error('Error response status:', lastError.response?.status)
        console.error('Error response data:', lastError.response?.data)
        if (lastError.response?.status === 404) {
        } else if (lastError.response?.status === 401) {
          console.error('SupaData API key authentication failed')
        } else if (lastError.response?.status === 403) {
          console.error('SupaData API key forbidden - check permissions')
        } else if (lastError.code === 'ECONNABORTED' || lastError.code === 'ETIMEDOUT') {
          console.error('SupaData request timed out - service may be slow')
        } else if (lastError.response?.status >= 500) {
          console.error('SupaData server error - service may be temporarily down')
        }
        // Continue to fallback methods
      }
    } else {
    }

    // Method 3: Try youtube-captions-scraper (JavaScript package)
    try {
      // Create a timeout promise
      const timeoutPromise = new Promise((_, reject) => {
        setTimeout(() => reject(new Error('youtube-captions-scraper timeout')), 5000)
      })

      // Race between getting captions and timeout
      let captions: any[] = []

      // First try to get Japanese captions
      try {
        captions = (await Promise.race([
          getSubtitles({
            videoID: videoId!,
            lang: 'ja',
          }),
          timeoutPromise,
        ])) as any[]
      } catch (jaError: any) {
        // Continue to next method
      }

      if (captions && captions.length > 0) {
        // Convert to our format
        const transcript = captions.map((caption: any, index: number) => ({
          id: String(index + 1),
          text: caption.text || '',
          startTime: (caption.start || 0) / 1000, // Convert ms to seconds
          endTime: ((caption.start || 0) + (caption.dur || 5000)) / 1000,
          words: (caption.text || '').split(/[\s、。！？]/g).filter((w: string) => w.length > 0),
        }))

        // Save to cache only for authenticated users
        if (isAuthenticated) {
          try {
            await transcriptCache.set({
              contentId,
              contentType: 'youtube',
              videoUrl: url,
              videoTitle: videoMetadata?.title || `YouTube Video ${videoId}`,
              transcript,
              language: 'ja',
              metadata: {
                youtubeVideoId: videoId,
                channelName: videoMetadata?.channelTitle,
                uploadDate: videoMetadata?.publishedAt,
                thumbnailUrl:
                  videoMetadata?.thumbnails?.medium?.url || videoMetadata?.thumbnails?.default?.url,
                duration: videoMetadata?.duration,
              },
            })
          } catch (cacheError) {
            console.error('Failed to cache youtube-captions-scraper transcript:', cacheError)
          }
        } else {
        }

        return NextResponse.json({
          success: true,
          transcript,
          language: 'ja',
          isAutoGenerated: false, // youtube-captions-scraper doesn't provide this info
          videoTitle: videoMetadata?.title || `YouTube Video ${videoId}`,
          videoMetadata: videoMetadata,
          method: 'youtube-captions-scraper',
        })
      }
    } catch (captionScraperError: any) {
      console.error('youtube-captions-scraper error:', captionScraperError.message)
      // Continue to next fallback method
    }

    // No captions found - check why

    // Check if API keys are configured
    const missingApis = []
    if (!process.env.SUPA_YOUTUBE_API_KEY) {
      missingApis.push('SupaData API')
    }
    if (!process.env.YOUTUBE_API_KEY && !process.env.GOOGLE_API_KEY) {
      missingApis.push('YouTube/Google API')
    }

    // Provide more specific error message
    let errorMessage =
      'This video does not have Japanese captions available. Try uploading the audio for AI transcription.'
    let errorCode = 'NO_CAPTIONS'
    let suggestions = [
      'Try uploading the audio file directly for AI transcription',
      'Check if the video has Japanese captions enabled on YouTube',
      'Try a different video with Japanese subtitles',
    ]

    // Check if we have a specific error to report
    if (missingApis.length > 0) {
      errorMessage = `API keys not configured: ${missingApis.join(', ')}. Please add the required API keys to enable transcript extraction.`
      errorCode = 'MISSING_API_KEYS'
      suggestions = [
        `Add ${missingApis.join(' and ')} keys to .env.local`,
        'SupaData API provides fallback transcript extraction when YouTube captions are unavailable',
        'See documentation for how to obtain these API keys',
      ]
    } else if (hitRateLimit) {
      errorMessage =
        'Our transcript service has reached its monthly limit. Please try again later or upload the audio directly for AI transcription.'
      errorCode = 'RATE_LIMIT'
    }

    return NextResponse.json({
      success: false,
      error: errorCode,
      message: errorMessage,
      videoTitle: videoMetadata?.title,
      videoMetadata: videoMetadata,
      suggestions: suggestions,
    })
  } catch (error) {
    console.error('=== API route critical error ===')
    console.error('Error:', error)
    console.error('Error stack:', error instanceof Error ? error.stack : 'No stack trace')

    return NextResponse.json(
      {
        error: 'Failed to process request',
        details: error instanceof Error ? error.message : 'Unknown error',
        stack:
          process.env.NODE_ENV === 'development'
            ? error instanceof Error
              ? error.stack
              : undefined
            : undefined,
      },
      { status: 500 }
    )
  }
}

function parseYouTubeCaptions(data: string): any[] {
  const transcript: any[] = []

  try {
    if (typeof data === 'string') {
      if (data.includes('<text')) {
        // Parse XML format
        const textRegex = /<text\s+start="([\d.]+)"\s+dur="([\d.]+)"[^>]*>([^<]+)<\/text>/g
        let match
        let index = 1

        while ((match = textRegex.exec(data)) !== null) {
          const start = parseFloat(match[1])
          const duration = parseFloat(match[2])
          const text = match[3]
            .replace(/&amp;/g, '&')
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/&quot;/g, '"')
            .replace(/&#39;/g, "'")
            .replace(/\n/g, ' ')
            .trim()

          if (text) {
            transcript.push({
              id: String(index++),
              text: text,
              startTime: start,
              endTime: start + duration,
              words: text.split(/[\s、。！？]/g).filter((w: string) => w.length > 0),
            })
          }
        }
      } else if (data.startsWith('{') || data.startsWith('[')) {
        // Parse JSON format
        const json = JSON.parse(data)
        const events = json.events || json

        if (Array.isArray(events)) {
          events.forEach((event: any, index: number) => {
            if (event.segs || event.text) {
              const text = event.text || event.segs.map((s: any) => s.utf8).join('')
              const start = (event.tStartMs || event.start || 0) / 1000
              const duration = (event.dDurationMs || event.dur || 5000) / 1000

              transcript.push({
                id: String(index + 1),
                text: text.trim(),
                startTime: start,
                endTime: start + duration,
                words: text
                  .trim()
                  .split(/[\s、。！？]/g)
                  .filter((w: string) => w.length > 0),
              })
            }
          })
        }
      }
    }
  } catch (error) {
    console.error('Error parsing captions:', error)
  }

  return transcript
}

function parseSupaDataTranscript(data: any): any[] {
  const transcript: any[] = []

  try {
    // SupaData returns data in format: { lang: 'ja', content: [...], availableLangs: [...] }
    if (data.content && Array.isArray(data.content)) {
      data.content.forEach((segment: any, index: number) => {
        // Convert milliseconds to seconds
        const startTime = (segment.offset || 0) / 1000
        const duration = (segment.duration || 5000) / 1000
        const endTime = startTime + duration

        transcript.push({
          id: String(index + 1),
          text: segment.text || '',
          startTime: startTime,
          endTime: endTime,
          words: (segment.text || '').split(/[\s、。！？]/g).filter((w: string) => w.length > 0),
        })
      })
    }
    // Fallback for other possible formats
    else if (data.transcript) {
      // If it's already formatted as an array of segments
      if (Array.isArray(data.transcript)) {
        data.transcript.forEach((segment: any, index: number) => {
          transcript.push({
            id: String(index + 1),
            text: segment.text || segment.content || '',
            startTime: segment.start || segment.startTime || index * 5,
            endTime: segment.end || segment.endTime || (index + 1) * 5,
            words: (segment.text || segment.content || '')
              .split(/[\s、。！？]/g)
              .filter((w: string) => w.length > 0),
          })
        })
      }
      // If it's a plain text transcript
      else if (typeof data.transcript === 'string') {
        // Split by sentences or paragraphs and create segments
        const sentences = data.transcript.split(/[。！？\n]+/).filter((s: string) => s.trim())
        const avgDuration = 5 // 5 seconds per segment as default

        sentences.forEach((sentence: string, index: number) => {
          transcript.push({
            id: String(index + 1),
            text: sentence.trim(),
            startTime: index * avgDuration,
            endTime: (index + 1) * avgDuration,
            words: sentence
              .trim()
              .split(/[\s、。！？]/g)
              .filter((w: string) => w.length > 0),
          })
        })
      }
    }
  } catch (error) {
    console.error('Error parsing SupaData transcript:', error)
  }

  return transcript
}
