# Production Monitoring Alerts Configuration
# SRE Agent 2 - Week 3 Production Deployment
# Generated: Monday - Alert Configuration

# ============================================
# CRITICAL ALERTS - Immediate Action Required
# ============================================

alerts:
  # Error Rate Monitoring
  - name: high_error_rate_critical
    metric: error_rate
    condition: "> 5%"
    duration: 1m
    severity: critical
    channels:
      - pagerduty
      - slack_critical
      - email_oncall
    description: "Error rate exceeds 5% - Immediate rollback may be required"
    runbook_url: "/runbooks/high-error-rate.md"
    
  - name: high_error_rate_warning
    metric: error_rate
    condition: "> 1%"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
      - email_team
    description: "Error rate exceeds 1% - Investigation required"
    
  # Response Time Monitoring
  - name: high_latency_critical
    metric: response_time_p95
    condition: "> 1000ms"
    duration: 2m
    severity: critical
    channels:
      - pagerduty
      - slack_critical
    description: "P95 response time exceeds 1 second"
    
  - name: high_latency_warning
    metric: response_time_p95
    condition: "> 500ms"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
    description: "P95 response time exceeds 500ms"
    
  # Sync System Monitoring
  - name: sync_failure_critical
    metric: sync_failure_rate
    condition: "> 5%"
    duration: 2m
    severity: critical
    channels:
      - pagerduty
      - slack_critical
    description: "Offline sync failure rate critical"
    
  # Database Health
  - name: database_connection_pool_exhausted
    metric: db_connection_pool_available
    condition: "< 5"
    duration: 1m
    severity: critical
    channels:
      - pagerduty
      - slack_critical
    description: "Database connection pool nearly exhausted"
    
  - name: database_replication_lag
    metric: db_replication_lag_seconds
    condition: "> 10"
    duration: 2m
    severity: warning
    channels:
      - slack_alerts
    description: "Database replication lag exceeds 10 seconds"

# ============================================
# WARNING ALERTS - Proactive Monitoring
# ============================================

  # Memory Usage
  - name: high_memory_usage_warning
    metric: memory_usage_percent
    condition: "> 80"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
    description: "Memory usage exceeds 80%"
    
  - name: high_memory_usage_critical
    metric: memory_usage_percent
    condition: "> 95"
    duration: 2m
    severity: critical
    channels:
      - pagerduty
      - slack_critical
    description: "Memory usage critical - OOM risk"
    
  # CPU Usage
  - name: high_cpu_usage
    metric: cpu_usage_percent
    condition: "> 80"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
    description: "CPU usage exceeds 80%"
    
  # Disk Usage
  - name: disk_space_warning
    metric: disk_usage_percent
    condition: "> 80"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
      - email_team
    description: "Disk usage exceeds 80%"
    
  - name: disk_space_critical
    metric: disk_usage_percent
    condition: "> 90"
    duration: 2m
    severity: critical
    channels:
      - pagerduty
      - slack_critical
    description: "Disk space critical"

# ============================================
# BUSINESS METRICS ALERTS
# ============================================

  # User Experience
  - name: low_session_completion_rate
    metric: session_completion_rate
    condition: "< 70%"
    duration: 10m
    severity: warning
    channels:
      - slack_product
    description: "Session completion rate below 70%"
    
  - name: high_session_abandonment
    metric: session_abandonment_rate
    condition: "> 30%"
    duration: 10m
    severity: warning
    channels:
      - slack_product
    description: "High session abandonment rate"
    
  # SRS Algorithm Performance
  - name: srs_calculation_slow
    metric: srs_calculation_time_p95
    condition: "> 100ms"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
    description: "SRS calculations taking too long"
    
  # Queue Generation
  - name: queue_generation_failure
    metric: queue_generation_success_rate
    condition: "< 95%"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
    description: "Queue generation failures detected"

# ============================================
# INFRASTRUCTURE ALERTS
# ============================================

  # Redis Cache
  - name: redis_connection_failure
    metric: redis_connected
    condition: "== 0"
    duration: 30s
    severity: critical
    channels:
      - pagerduty
      - slack_critical
    description: "Redis connection lost"
    
  - name: redis_high_memory
    metric: redis_memory_usage_percent
    condition: "> 90"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
    description: "Redis memory usage high"
    
  - name: cache_hit_rate_low
    metric: cache_hit_rate
    condition: "< 60%"
    duration: 10m
    severity: info
    channels:
      - slack_alerts
    description: "Cache hit rate below expected"
    
  # External Services
  - name: stripe_api_errors
    metric: stripe_api_error_rate
    condition: "> 1%"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
      - email_finance
    description: "Stripe API errors detected"
    
  - name: tts_provider_failure
    metric: tts_provider_success_rate
    condition: "< 95%"
    duration: 5m
    severity: warning
    channels:
      - slack_alerts
    description: "TTS provider issues detected"

# ============================================
# SECURITY ALERTS
# ============================================

  - name: suspicious_traffic_spike
    metric: request_rate_per_ip
    condition: "> 1000"
    duration: 1m
    severity: warning
    channels:
      - slack_security
    description: "Suspicious traffic spike from single IP"
    
  - name: authentication_failure_spike
    metric: auth_failure_rate
    condition: "> 50"
    duration: 5m
    severity: warning
    channels:
      - slack_security
      - email_security
    description: "High authentication failure rate"
    
  - name: rate_limit_bypassed
    metric: rate_limit_bypass_attempts
    condition: "> 10"
    duration: 5m
    severity: critical
    channels:
      - pagerduty
      - slack_security
    description: "Rate limit bypass attempts detected"

# ============================================
# DEPLOYMENT-SPECIFIC ALERTS (Thursday)
# ============================================

  - name: deployment_rollout_error_spike
    metric: error_rate
    condition: "> 2%"
    duration: 30s
    severity: critical
    channels:
      - pagerduty
      - slack_deployment
    description: "Error spike during deployment - consider rollback"
    active_during: "deployment_window"
    
  - name: deployment_traffic_anomaly
    metric: traffic_distribution
    condition: "deviation > 20%"
    duration: 1m
    severity: warning
    channels:
      - slack_deployment
    description: "Traffic distribution anomaly during deployment"
    active_during: "deployment_window"

# ============================================
# ALERT CHANNELS CONFIGURATION
# ============================================

channels:
  pagerduty:
    type: pagerduty
    integration_key: "${PAGERDUTY_INTEGRATION_KEY}"
    escalation_policy: "production-critical"
    
  slack_critical:
    type: slack
    webhook_url: "${SLACK_CRITICAL_WEBHOOK}"
    channel: "#prod-critical"
    mention: "@oncall"
    
  slack_alerts:
    type: slack
    webhook_url: "${SLACK_ALERTS_WEBHOOK}"
    channel: "#prod-alerts"
    
  slack_deployment:
    type: slack
    webhook_url: "${SLACK_DEPLOYMENT_WEBHOOK}"
    channel: "#deployment-war-room"
    mention: "@deployment-team"
    
  slack_product:
    type: slack
    webhook_url: "${SLACK_PRODUCT_WEBHOOK}"
    channel: "#product-metrics"
    
  slack_security:
    type: slack
    webhook_url: "${SLACK_SECURITY_WEBHOOK}"
    channel: "#security-alerts"
    mention: "@security"
    
  email_oncall:
    type: email
    recipients:
      - oncall@company.com
    
  email_team:
    type: email
    recipients:
      - engineering@company.com
    
  email_security:
    type: email
    recipients:
      - security@company.com
    
  email_finance:
    type: email
    recipients:
      - finance@company.com

# ============================================
# ALERT AGGREGATION RULES
# ============================================

aggregation_rules:
  - name: "Suppress duplicate alerts"
    window: 5m
    max_alerts: 3
    
  - name: "Correlate related alerts"
    correlate:
      - high_error_rate_*
      - high_latency_*
    as: "system_degradation"
    
  - name: "Escalate repeated warnings"
    condition: "warning_count > 5 in 30m"
    escalate_to: critical

# ============================================
# MAINTENANCE WINDOWS
# ============================================

maintenance_windows:
  - name: "Weekly maintenance"
    schedule: "0 2 * * SUN"  # Sunday 2 AM
    duration: 2h
    suppress_alerts:
      - disk_space_warning
      - cache_hit_rate_low
    
  - name: "Deployment window"
    schedule: "manual"
    duration: 4h
    modify_alerts:
      all:
        reduce_sensitivity: 50%