apiVersion: v1
kind: ConfigMap
metadata:
  name: moshimoshi-config
  namespace: moshimoshi
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  SENTRY_ENVIRONMENT: "production"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_MAX_RETRIES: "3"
  REDIS_RETRY_DELAY: "1000"
  
  # Firestore Configuration
  FIRESTORE_MAX_CONNECTIONS: "10"
  FIRESTORE_MIN_CONNECTIONS: "2"
  FIRESTORE_CONNECTION_TIMEOUT: "10000"
  FIRESTORE_IDLE_TIMEOUT: "60000"
  FIRESTORE_MAX_RETRIES: "3"
  
  # Monitoring
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30000"