apiVersion: v1
kind: Secret
metadata:
  name: moshimoshi-secrets
  namespace: moshimoshi
type: Opaque
stringData:
  # Replace these with base64 encoded values in production
  FIREBASE_ADMIN_PROJECT_ID: "your-project-id"
  FIREBASE_ADMIN_CLIENT_EMAIL: "your-client-email"
  FIREBASE_ADMIN_PRIVATE_KEY: "your-private-key"
  
  UPSTASH_REDIS_REST_URL: "your-upstash-url"
  UPSTASH_REDIS_REST_TOKEN: "your-upstash-token"
  
  STRIPE_SECRET_KEY: "your-stripe-secret"
  STRIPE_WEBHOOK_SECRET: "your-webhook-secret"
  
  NEXT_PUBLIC_SENTRY_DSN: "your-sentry-dsn"
  SENTRY_AUTH_TOKEN: "your-sentry-auth-token"
  
  REDIS_PASSWORD: "your-redis-password"
  REDIS_CONFIG_PASSWORD: "your-redis-config-password"
  
  METRICS_API_KEY: "your-metrics-api-key"