import { NextRequest, NextResponse } from 'next/server';
import axios from 'axios';

const YOUTUBE_API_BASE = 'https://www.googleapis.com/youtube/v3';

interface CaptionTrack {
  language: string;
  name: string;
  isManual: boolean;
  isAutoGenerated: boolean;
  trackId: string;
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const videoId = searchParams.get('videoId');

  if (!videoId) {
    return NextResponse.json({ error: 'videoId parameter required' }, { status: 400 });
  }

  const apiKey = process.env.GOOGLE_API_KEY || process.env.YOUTUBE_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: 'YouTube API key not configured' }, { status: 500 });
  }

  try {
    const response = await axios.get(`${YOUTUBE_API_BASE}/captions`, {
      params: {
        part: 'snippet',
        videoId: videoId,
        key: apiKey
      },
      timeout: 10000
    });

    const tracks: CaptionTrack[] = response.data.items.map((track: any) => ({
      language: track.snippet.language,
      name: track.snippet.name,
      isManual: track.snippet.trackKind !== 'ASR',
      isAutoGenerated: track.snippet.trackKind === 'ASR',
      trackId: track.id
    }));

    return NextResponse.json({
      success: true,
      tracks: tracks,
      hasJapanese: tracks.some(track =>
        track.language === 'ja' || track.language.startsWith('ja-')
      )
    });

  } catch (error: any) {
    console.error('Caption detection error:', error.response?.data || error.message);

    if (error.response?.status === 403) {
      return NextResponse.json({
        success: false,
        error: 'API_QUOTA_EXCEEDED',
        message: 'YouTube API quota exceeded'
      }, { status: 403 });
    }

    if (error.response?.status === 404) {
      return NextResponse.json({
        success: false,
        error: 'VIDEO_NOT_FOUND',
        message: 'Video not found or captions not available'
      }, { status: 404 });
    }

    return NextResponse.json({
      success: false,
      error: 'CAPTION_DETECTION_FAILED',
      message: 'Could not retrieve caption information'
    }, { status: 500 });
  }
}